### ISSUE TITLE
Create A Readme for the project

### ISSUE THREAD

**Issue by arjundubey-cr** [Coding-Connoisseurs/coding-connoisseurs.github.io#8]
Readme file for the project.

**Comment by vikaskumar2703** [comment]
i can create a readme for the repo pl assign me this issue

**Comment by SiddharthaMishra-dev** [comment]
You can fork this repo and create the Readme.

**Comment by vikaskumar2703** [comment]
what all should it contain ? just like other projects have.

**Comment by SiddharthaMishra-dev** [comment]
yeah...like how to install, file structure and how to make change..

**Comment by kartik-gupta-ij** [comment]
> what all should it contain ? just like other projects have.

- [ ] Project Description: Provide a brief overview of the project or the purpose of the website.

- [x] Technologies Used: List out the programming languages, frameworks, and tools used to build the website.

- [x] Installation Instructions: Include clear, step-by-step instructions on how to install and run the project locally.

- [ ] Getting Started: Explain how users can get started with the project and any prerequisites they may need to have installed.

- [ ] Usage Instructions: Provide instructions on how to use the website or application, including any features or functionalities.

- [x] Contributing Guidelines: Detail how users can contribute to the project, including guidelines for submitting bug reports, feature requests, and pull requests.

- [ ] License Information: Specify the type of license used for the project and any terms and conditions that apply.

- [x] Project Structure: Provide an overview of the folder and file structure of the project.

- [x] Contact Information: Include contact information for the project maintainer or contributors, such as an email address or link to a GitHub profile.

- [ ] Acknowledgments: Give credit to any third-party libraries or resources used in the project, as well as any contributors who have helped with the development.

**Comment by vikaskumar2703** [comment]
what all tech stack has been used

**Comment by vikaskumar2703** [comment]
whose contact information is to be provided

**Comment by vikaskumar2703** [comment]
@SiddharthaMishra-dev @kartik-gupta-ij i have submitted a pr check it out and suggest changes

**Comment by SiddharthaMishra-dev** [comment]
Okay .we'll check

**Comment by vikaskumar2703** [comment]
@SiddharthaMishra-dev  close this issue
